### ISSUE TITLE
How to building from a branch other than master?

### ISSUE THREAD

**Issue by Lissy93** [redkubes/docusaurus-deploy-action#1]
Hey @Morriz  
You're action looks awesome, just a quick question- Is it possible to select a different input branch? Or would I need to fork it in order to modify this? 

For example, I have [a project](https://github.com/Lissy93/dashy), which has the main project code on the master branch, Docourousrus's code on another branch, and I would like Docusourus to build the to the gh-pages branch.
If I were to modify this, as a fork, do you know I would to add to change in [`entrypoint.sh`](https://github.com/redkubes/docusaurus-deploy-action/blob/master/entrypoint.sh), as a starting point?

Thanks very much, and keep up the great work :)
Alicia

**Comment by Morriz** [comment]
Hey there, your github workflow can be triggered on any branch/condition. That is in their docs and without the scope of this action ;) I think their docs are rather large and unclear sometimes, but that info you can find for sure. Good luck!
