### ISSUE TITLE
Latest version throws an error: Unable to resolve dependency tree

### ISSUE THREAD

**Issue by Lissy93** [redkubes/docusaurus-deploy-action#3]
Heya @Morriz

Thanks for building and maintaining this action, it's been really useful :)

Noticed the version in the master branch seems to have broken. Here's the build output [Lissy93/dashy - run 6843821601](https://github.com/Lissy93/dashy/runs/6843821601)
It throws `ERESOLVE unable to resolve dependency tree` with the `@docusaurus/core@2.0.0-beta.2` and `docusaurus-plugin-sass@0.2.1` dependencies. 

But upon [downgrading to V1](https://github.com/Lissy93/dashy/commit/0015db1b33c43cf14fd1b2b5efadc9352e2e5bca), the action then runs as expected. For comparison, the build output:  [Lissy93/dashy - run 6843850560](https://github.com/Lissy93/dashy/runs/6843850560).

Not sure if it's something that I am doing wrong in my workflow, or if it's a bug with the latest version of this action.
Anyway, thought I would share this, in case anyone else was having a similar issue, or you weren't aware of it.

Thanks :)

**Comment by Morriz** [comment]
Hi, Tnx. Github actions suggest tagging to major versions, and v1.2 is now latest and linked to v1.

As you might see in the plugin not much is going on in there and we have opted into the docusaurus example github workflow ourselves. So I am going to add a deprecation warning soon pointing to their docs ;)

**Comment by Lissy93** [comment]
Cool, thanks for your reply :)
I'll migrate over to Docusaurus's workflow when I get a moment then
Have a great weekend!
